openapi: 3.0.0
info:
  title: specialist
  version: '1.0'
servers:
  - url: 'http://localhost:3000/api/specialist'
paths: {}
components:
  schemas: {}
  securitySchemes:
    API Key - 1:
      type: http
      scheme: basic
